In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_iris
iris_dataset=load_iris()
print("iris_dataset의 키:\n", iris_dataset.keys())

iris_dataset의 키:
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
!pip install joblib==1.1.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.0/307.0 KB 6.3 MB/s eta 0:00:00
  Attempting uninstall: joblib
    Found existing installation: joblib 1.2.0
    Uninstalling joblib-1.2.0:
      Successfully uninstalled joblib-1.2.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scikit-learn 1.2.0 requires joblib>=1.1.1, but you have joblib 1.1.0 which is incompatible.


In [ ]:
print(iris_dataset['target_names'])
print(iris_dataset['feature_names'])

['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [ ]:
print(iris_dataset['data'][:5])
import seaborn as sns
iris_dataset2=sns.load_dataset('iris')
iris_dataset2.head()

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
print(iris_dataset['target'])
print(type(iris_dataset['target']))
print(iris_dataset['target'].shape)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
<class 'numpy.ndarray'>
(150,)


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=0)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(type(X_train.shape))
print(type(X_test.shape))
print(y_train.shape)
print(y_test.shape)
print(type(y_train.shape))
print(type(y_test.shape))

(112, 4)
(38, 4)
<class 'tuple'>
<class 'tuple'>
(112,)
(38,)
<class 'tuple'>
<class 'tuple'>


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import mglearn

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


ImportError: ignored

In [ ]:
Iris_dataframe=pd.DataFrame(X_train, columns=Iris_dataset.feature_names)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

In [ ]:
knn.fit(X_train, y_train)

In [ ]:
X_new = np.array([[5,2,9,1]])
print(X_new.shape)

prediction=knn.predict(X_new)
print("prediction result", prediction)
print("target name of prediction result", Iris_dataset['target_names'][prediction])

In [ ]:
y_pred = knn.predict(X_test)
print("prediction result of test dataset", y_pred)

In [ ]:
print("테스트 세트의 정확도: {:.3f}".format(np.mean(y_pred==y_test)))